[project]
name = "Kapowarr"
version = "1.3.1"
description = "Kapowarr is a software to build and manage a comic book library, fitting in the *arr suite of software."
authors = [
    {name = "Cas van Tijn"}
]
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">= 3.13"

dependencies = [
    "aiohttp ~= 3.9",
    "beautifulsoup4 ~= 4.12",
    "bencoding ~= 0.2",
    "cryptography >= 46.0.5, < 47.0",
    "flask ~= 3.0",
    "flask-socketio ~= 5.3",
    "requests[socks] ~= 2.31",
    "waitress ~= 3.0",
    "websocket-client ~= 1.3"
]

[dependency-groups]
dev = [
    "pre-commit ~= 3.5",
    "ruff",
    "ty"
]

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",      # pycodestyle
    "F",      # pyflakes
    "I",      # isort
    "UP",     # pyupgrade
    "S",      # flake8-bandit
    "B",      # flake8-bugbear
    "ASYNC",  # flake8-async
    "SIM",    # flake8-simplify
    "C4",     # flake8-comprehensions
    "RUF",    # Ruff-specific rules
    "ANN"     # flake8-annotations
]

[tool.ruff.lint.isort]
combine-as-imports = true